Repository NCSU-High-Powered-Rocketry-Club/AirbrakesV2, pull requests merged in 2024-11, with the labels that each got.

#47 Implement Apogee Prediction
  README.md
  airbrakes/airbrakes.py
  airbrakes/data_handling/apogee_predictor.py
  airbrakes/data_handling/data_processor.py
  airbrakes/data_handling/logged_data_packet.py
  airbrakes/data_handling/logger.py
  airbrakes/data_handling/processed_data_packet.py
  airbrakes/mock/display.py
  airbrakes/state.py
  constants.py
  main.py
  pyproject.toml
  tests/conftest.py
  tests/imu_data/README.md
  tests/imu_data/xminus.csv
  tests/imu_data/xplus.csv
  tests/imu_data/yminus.csv
  tests/imu_data/yplus.csv
  tests/imu_data/zminus.csv
  tests/imu_data/zplus.csv
  tests/test_airbrakes.py
  tests/test_apogee_predictor.py
  tests/test_data_processor.py
  tests/test_integration.py
  tests/test_logged_data_packet.py
  tests/test_logger.py
  tests/test_processed_data_packet.py
  tests/test_state.py
Labels: enhancement

#72 Add ruff as pre-commit hook
  .github/workflows/ruff.yml
  .pre-commit-config.yaml
  README.md
  pyproject.toml
Labels: misc

#73 Enforce Line length to 100
  airbrakes/airbrakes.py
  airbrakes/data_handling/apogee_predictor.py
  airbrakes/data_handling/data_processor.py
  airbrakes/data_handling/imu_data_packet.py
  airbrakes/data_handling/logged_data_packet.py
  airbrakes/data_handling/logger.py
  airbrakes/data_handling/processed_data_packet.py
  airbrakes/hardware/imu.py
  airbrakes/hardware/servo.py
  airbrakes/mock/display.py
  airbrakes/mock/mock_imu.py
  airbrakes/state.py
  constants.py
  main.py
  pyproject.toml
  tests/conftest.py
  tests/test_airbrakes.py
  tests/test_apogee_predictor.py
  tests/test_data_processor.py
  tests/test_imu.py
  tests/test_integration.py
  tests/test_logged_data_packet.py
  tests/test_logger.py
  tests/test_state.py
  utils.py
Labels: misc

#74 Added liftoff time to display
  airbrakes/mock/display.py
Labels: enhancement

#71 Adding Air Brakes Control
  airbrakes/airbrakes.py
  airbrakes/data_handling/apogee_predictor.py
  airbrakes/mock/display.py
  airbrakes/state.py
  constants.py
  tests/test_apogee_predictor.py
  tests/test_state.py
Labels: enhancement

#79 Retract airbrakes when under target apogee, remove no buzz condition
  airbrakes/hardware/servo.py
  airbrakes/state.py
  constants.py
  scripts/run_servo.py
  scripts/startup.py
  tests/test_airbrakes.py
  tests/test_state.py
Labels: enhancement

#82 Use `pandas` for reading mock sim file, add debug output on display
  airbrakes/airbrakes.py
  airbrakes/mock/display.py
  airbrakes/mock/mock_imu.py
  pyproject.toml
Labels: enhancement

#81 Refactor logging architecture
  airbrakes/data_handling/logged_data_packet.py
  airbrakes/data_handling/logger.py
  tests/test_integration.py
  tests/test_logged_data_packet.py
  tests/test_logger.py
Labels: bug, enhancement

#88 added pressure field to packets
  airbrakes/data_handling/imu_data_packet.py
  airbrakes/data_handling/logged_data_packet.py
Labels: enhancement, hardware

#89 Fixes with the full stack
  airbrakes/hardware/imu.py
  airbrakes/hardware/servo.py
  airbrakes/mock/display.py
  airbrakes/state.py
  constants.py
  main.py
  utils.py
Labels: bug, do not merge (yet)

#93 Fix display disappearance, add new field, fix ctrl-c
  airbrakes/hardware/imu.py
  airbrakes/mock/display.py
  constants.py
  utils.py
Labels: bug

#102 Add `.gitattributes` to change Github's detection of language
  .gitattributes
Labels: misc

#98 Fix servo control
  airbrakes/hardware/servo.py
  tests/conftest.py
  tests/test_servo.py
  tests/test_state.py
Labels: bug
