Repository NCSU-High-Powered-Rocketry-Club/AirbrakesV2, pull requests merged in 2024-09, with the labels that each got.

#1 Add `__slots__` to classes for performance improvements
  Airbrakes/airbrakes.py
  Airbrakes/imu.py
  Airbrakes/logger.py
  Airbrakes/servo.py
  Airbrakes/state.py
  Scripts/test_imu.py
  Scripts/test_logger.py
  Scripts/test_servo.py
  main.py
Labels: enhancement

#2 Add Ruff as a formatter and linter
  .github/workflows/ruff.yml
  Airbrakes/__init__.py
  Airbrakes/airbrakes.py
  Airbrakes/imu.py
  Airbrakes/logger.py
  Airbrakes/servo.py
  Airbrakes/state.py
  Scripts/__init__.py
  Scripts/test_logger.py
  Scripts/test_servo.py
  main.py
  pyproject.toml
Labels: enhancement

#4 Architecture and logging improvements, packets batch processing
  Airbrakes/airbrakes.py
  Airbrakes/imu.py
  Airbrakes/utils.py
  Scripts/test_imu.py
  Scripts/test_logger.py
  Scripts/test_servo.py
  airbrakes/__init__.py
  airbrakes/airbrakes.py
  airbrakes/constants.py
  airbrakes/imu/__init__.py
  airbrakes/imu/data_processor.py
  airbrakes/imu/imu.py
  airbrakes/imu/imu_data_packet.py
  airbrakes/logger.py
  airbrakes/servo.py
  airbrakes/state.py
  main.py
  requirements.txt
Labels: enhancement

#5 Better encapsulation for the `Logger` & `IMU` class and fix a bug
  airbrakes/airbrakes.py
  airbrakes/constants.py
  airbrakes/imu/imu.py
  airbrakes/imu/imu_data_packet.py
  airbrakes/logger.py
  main.py
Labels: enhancement

#8 Use the `msgspec` library for `IMUDataPacket` classes
  airbrakes/constants.py
  airbrakes/imu/imu_data_packet.py
  airbrakes/logger.py
  requirements.txt
  tests/test_logger.py
Labels: enhancement

#6 Start unit tests with `pytest`
  .github/workflows/unit_tests.yml
  Scripts/run_imu.py
  Scripts/run_logger.py
  Scripts/run_servo.py
  airbrakes/constants.py
  airbrakes/imu/imu_data_packet.py
  airbrakes/logger.py
  pyproject.toml
  requirements.txt
  tests/__init__.py
  tests/conftest.py
  tests/test_logger.py
Labels: enhancement, tests

#10 More unit tests, fix bug when running `main.py`
  airbrakes/airbrakes.py
  airbrakes/imu/data_processor.py
  airbrakes/imu/imu.py
  airbrakes/logger.py
  airbrakes/servo.py
  airbrakes/state.py
  pyproject.toml
  requirements.txt
  scripts/run_imu.py
  scripts/run_servo.py
  tests/conftest.py
  tests/test_airbrakes.py
  tests/test_data_processor.py
  tests/test_imu.py
  tests/test_imu_data_packet.py
  tests/test_logger.py
Labels: bug, tests

#13 Fix quaternion logging
  airbrakes/constants.py
  airbrakes/imu/imu.py
Labels: bug

#11 Adjust servo extension values
  airbrakes/constants.py
  pyproject.toml
  scripts/run_imu.py
Labels: hardware

#15 Changed project structure
  .github/workflows/unit_tests.yml
  airbrakes/airbrakes.py
  airbrakes/data_handling/__init__.py
  airbrakes/data_handling/data_processor.py
  airbrakes/data_handling/imu_data_packet.py
  airbrakes/data_handling/logger.py
  airbrakes/hardware/__init__.py
  airbrakes/hardware/imu.py
  airbrakes/hardware/servo.py
  constants.py
  main.py
  pyproject.toml
  requirements.txt
  scripts/run_imu.py
  scripts/run_logger.py
  scripts/run_servo.py
  tests/conftest.py
  tests/test_data_processor.py
  tests/test_imu.py
  tests/test_imu_data_packet.py
  tests/test_logger.py
Labels: enhancement

#17 Adjust channels fetched from the IMU
  airbrakes/data_handling/imu_data_packet.py
  tests/test_imu_data_packet.py
Labels: enhancement

#16 Started writing sim code, also cleaned up IMU and State a little
  airbrakes/hardware/imu.py
  airbrakes/mock/__init__.py
  airbrakes/mock/mock_imu.py
  airbrakes/state.py
  main.py
  scripts/run_imu.py
  tests/conftest.py
  tests/test_imu.py
Labels: enhancement, help wanted

#18 Improvements to main.py
  airbrakes/airbrakes.py
  airbrakes/data_handling/data_processor.py
  constants.py
  main.py
  tests/conftest.py
  tests/test_airbrakes.py
Labels: enhancement

#14 Clean exit on Ctrl+C
  airbrakes/airbrakes.py
  airbrakes/data_handling/logger.py
  airbrakes/hardware/imu.py
  main.py
  pyproject.toml
  scripts/run_imu.py
  scripts/run_logger.py
  scripts/run_main_local.py
  scripts/run_servo.py
  tests/test_airbrakes.py
  tests/test_imu.py
  tests/test_logger.py
Labels: bug, enhancement

#20 Update README.md
  README.md
Labels: documentation

#22 Log data processor
  airbrakes/airbrakes.py
  airbrakes/data_handling/data_processor.py
  airbrakes/data_handling/logger.py
  airbrakes/utils.py
  constants.py
  scripts/run_logger.py
  tests/test_data_processor.py
  tests/test_logger.py
Labels: bug, enhancement

#24 Fix speed calculations - approach 1
  airbrakes/airbrakes.py
  airbrakes/data_handling/data_processor.py
  airbrakes/state.py
  airbrakes/utils.py
Labels: bug

#27 Update README.md
  README.md
Labels: documentation

#28 Add log buffer
  airbrakes/airbrakes.py
  airbrakes/data_handling/data_processor.py
  airbrakes/data_handling/logger.py
  airbrakes/state.py
  constants.py
  main.py
  tests/test_logger.py
  tests/test_state.py
Labels: enhancement
