Repository NCSU-High-Powered-Rocketry-Club/AirbrakesV2, pull requests merged in 2024-10, with the labels that each got.

#32 Log and use invalid data packets
  airbrakes/data_handling/imu_data_packet.py
  airbrakes/data_handling/logged_data_packet.py
  airbrakes/hardware/imu.py
  scripts/data_visualizer.py
  tests/test_imu.py
  tests/test_imu_data_packet.py
  tests/test_logger.py
Labels: enhancement

#39 Solved the mermaid diagram of #36
  README.md
Labels: documentation

#40 Performance Improvements
  README.md
  airbrakes/data_handling/data_processor.py
  airbrakes/data_handling/logged_data_packet.py
  airbrakes/data_handling/logger.py
  airbrakes/data_handling/processed_data_packet.py
  airbrakes/hardware/imu.py
  constants.py
  tests/test_data_processor.py
  tests/test_integration.py
  tests/test_logged_data_packet.py
  tests/test_processed_data_packet.py
Labels: enhancement

#45 Minor `MockIMU` performance improvements
  airbrakes/mock/mock_imu.py
  airbrakes/utils.py
Labels: enhancement

#48 Change `qsize()` to `.empty()`
  airbrakes/hardware/imu.py
Labels: bug

#44 Various Cleaning Up
  airbrakes/airbrakes.py
  airbrakes/data_handling/data_processor.py
  airbrakes/data_handling/logger.py
  airbrakes/mock/mock_imu.py
  constants.py
  main.py
  scripts/run_logger.py
  tests/conftest.py
  tests/test_airbrakes.py
  tests/test_data_processor.py
  tests/test_imu.py
  tests/test_integration.py
  tests/test_logger.py
Labels: enhancement

#50 Added comments
  airbrakes/airbrakes.py
  airbrakes/data_handling/data_processor.py
  airbrakes/data_handling/logger.py
  airbrakes/hardware/imu.py
  airbrakes/hardware/servo.py
  airbrakes/mock/mock_imu.py
  airbrakes/state.py
  constants.py
  main.py
  tests/test_integration.py
  tests/test_state.py
Labels: documentation

#49 Add `FlightDisplay` + some QoL improvements
  airbrakes/mock/display.py
  main.py
  pyproject.toml
  utils.py
Labels: enhancement

#51 `MockIMU` upgrades, better argument parsing, new `MockLogger` class
  README.md
  airbrakes/mock/mock_imu.py
  airbrakes/mock/mock_logger.py
  constants.py
  main.py
  utils.py
Labels: enhancement

#57 Tiny performance improvement, type hinting improvements
  airbrakes/data_handling/logged_data_packet.py
  airbrakes/data_handling/logger.py
  airbrakes/mock/mock_logger.py
  tests/test_logged_data_packet.py
  tests/test_logger.py
Labels: enhancement

#55 Run `FlightDisplay` in another thread, fix cpu usage
  airbrakes/mock/display.py
  main.py
Labels: enhancement

#58 Terminate `main.py` after we have landed and hit the buffer
  airbrakes/airbrakes.py
  airbrakes/data_handling/logger.py
  airbrakes/hardware/imu.py
  airbrakes/mock/mock_imu.py
  airbrakes/state.py
  constants.py
  main.py
  tests/test_imu.py
  tests/test_logger.py
  tests/test_state.py
Labels: bug, enhancement

#62 More tests
  airbrakes/data_handling/apogee_predictor.py
  airbrakes/data_handling/data_processor.py
  airbrakes/data_handling/processed_data_packet.py
  tests/test_airbrakes.py
  tests/test_data_processor.py
Labels: tests

#64 Rotation tests
  airbrakes/data_handling/data_processor.py
  tests/imu_data/xminus.csv
  tests/imu_data/xplus.csv
  tests/imu_data/yminus.csv
  tests/imu_data/yplus.csv
  tests/imu_data/zminus.csv
  tests/imu_data/zplus.csv
  tests/test_data_processor.py
Labels: enhancement

#66 Added coverage to workflow
  .github/workflows/integration_tests.yml
  .github/workflows/unit_tests.yml
  README.md
  pyproject.toml
Labels: tests

#67 Apogee pred tests
  airbrakes/data_handling/apogee_predictor.py
  airbrakes/data_handling/data_processor.py
  airbrakes/data_handling/logged_data_packet.py
  airbrakes/state.py
  constants.py
  tests/conftest.py
  tests/test_airbrakes.py
  tests/test_apogee_predictor.py
  tests/test_data_processor.py
  tests/test_integration.py
  tests/test_logged_data_packet.py
  tests/test_logger.py
  tests/test_processed_data_packet.py
  tests/test_state.py
Labels: tests

#69 Use `scipy` for rotations, improve performance of time differences by ~20%
  airbrakes/data_handling/data_processor.py
  tests/test_data_processor.py
Labels: enhancement
