Repository NCSU-High-Powered-Rocketry-Club/AirbrakesV2, pull requests merged in 2025-04, with the labels that each got.

#185 Fix pitch calculations
  .pre-commit-config.yaml
  airbrakes/mock/display.py
  airbrakes/mock/mock_imu.py
  airbrakes/telemetry/data_processor.py
  tests/auxil/utils.py
  tests/test_components/test_data_processor.py
Labels: bug

#187 Changing Convergence Thresholds
  airbrakes/constants.py
  tests/test_context.py
Labels: enhancement

#186 Switch to Pelicanator Launch 3 config
  airbrakes/constants.py
  launch_data/metadata.json
  pyproject.toml
  tests/conftest.py
  uv.lock
Labels: misc

#188 Servo rewrite launch day
  airbrakes/constants.py
  airbrakes/context.py
  airbrakes/hardware/servo.py
  airbrakes/interfaces/base_servo.py
  airbrakes/mock/mock_servo.py
  airbrakes/state.py
  scripts/run_imu.py
  scripts/run_servo_and_encoder.py
Labels: bug

#192 Add pelicanator launch 3 metadata
  README.md
  launch_data/README.md
  launch_data/metadata.json
  launch_data/videos/pelicanator_launch_3_airbrakes_deploy.gif
  tests/conftest.py
Labels: misc
