Repository NCSU-High-Powered-Rocketry-Club/AirbrakesV2, pull requests merged in 2025-01, with the labels that each got.

#122 #111 Refactor IMU: BaseIMU -> [MockIMU, IMU]
  .gitignore
  airbrakes/hardware/base_imu.py
  airbrakes/hardware/imu.py
  airbrakes/mock/mock_imu.py
Labels: tiny refactors

#121 Use `uv` to streamline setup and update README
  .github/workflows/integration_tests.yml
  .github/workflows/unit_tests.yml
  README.md
  airbrakes/airbrakes.py
  airbrakes/constants.py
  airbrakes/data_handling/apogee_predictor.py
  airbrakes/data_handling/data_processor.py
  airbrakes/data_handling/logger.py
  airbrakes/hardware/imu.py
  airbrakes/hardware/servo.py
  airbrakes/main.py
  airbrakes/mock/display.py
  airbrakes/mock/mock_imu.py
  airbrakes/state.py
  airbrakes/utils.py
  legacy_project_setup.md
  pyproject.toml
  scripts/run_imu.py
  scripts/run_logger.py
  scripts/run_servo.py
  tests/conftest.py
  tests/test_airbrakes.py
  tests/test_apogee_predictor.py
  tests/test_imu.py
  tests/test_integration.py
  tests/test_logger.py
  tests/test_servo.py
  tests/test_state.py
  tests/test_utils.py
  uv.lock
Labels: documentation

#99 Use `faster-fifo` for queues & more performance improvements
  .github/workflows/integration_tests.yml
  README.md
  airbrakes/airbrakes.py
  airbrakes/data_handling/apogee_predictor.py
  airbrakes/data_handling/data_processor.py
  airbrakes/data_handling/logger.py
  airbrakes/hardware/base_imu.py
  airbrakes/hardware/imu.py
  airbrakes/mock/mock_imu.py
  constants.py
  pyproject.toml
  tests/auxil/__init__.py
  tests/auxil/utils.py
  tests/conftest.py
  tests/test_airbrakes.py
  tests/test_apogee_predictor.py
  tests/test_data_processor.py
  tests/test_imu.py
  tests/test_logger.py
  tests/test_utils.py
  utils.py
Labels: enhancement

#118 Use acceleration spike to switch to `LandedState`
  airbrakes/constants.py
  airbrakes/data_handling/data_processor.py
  airbrakes/state.py
  tests/test_data_processor.py
  tests/test_integration.py
  tests/test_state.py
Labels: bug

#128 Renaming "Mock Sim" to "Mock Replay"
  README.md
  airbrakes/constants.py
  airbrakes/hardware/imu.py
  airbrakes/main.py
  airbrakes/mock/display.py
  airbrakes/mock/mock_imu.py
  airbrakes/utils.py
  launch_data/README.md
  launch_data/metadata.json
  tests/conftest.py
  tests/test_airbrakes.py
  tests/test_apogee_predictor.py
  tests/test_data_processor.py
  tests/test_imu.py
Labels: tiny refactors

#126 Automatically install `mscl` via pip
  airbrakes/hardware/imu.py
  pyproject.toml
  uv.lock
Labels: hardware

#127 Rotary Encoder script
  airbrakes/constants.py
  airbrakes/hardware/servo.py
  pyproject.toml
  scripts/run_buzzer.py
  scripts/run_buzzer_gui.py
  scripts/run_servo_and_encoder.py
  uv.lock
Labels: hardware

#129 Using acceleration to switch to motor burn state
  airbrakes/constants.py
  airbrakes/state.py
  tests/test_integration.py
  tests/test_state.py
Labels: do not merge (yet)

#100 Adding more fields to log
  README.md
  airbrakes/airbrakes.py
  airbrakes/constants.py
  airbrakes/data_handling/apogee_predictor.py
  airbrakes/data_handling/data_processor.py
  airbrakes/data_handling/logger.py
  airbrakes/data_handling/packets/__init__.py
  airbrakes/data_handling/packets/apogee_predictor_data_packet.py
  airbrakes/data_handling/packets/context_data_packet.py
  airbrakes/data_handling/packets/imu_data_packet.py
  airbrakes/data_handling/packets/logger_data_packet.py
  airbrakes/data_handling/packets/processor_data_packet.py
  airbrakes/data_handling/packets/servo_data_packet.py
  airbrakes/hardware/base_imu.py
  airbrakes/hardware/imu.py
  airbrakes/mock/display.py
  airbrakes/mock/mock_imu.py
  airbrakes/state.py
  scripts/run_logger.py
  tests/auxil/utils.py
  tests/conftest.py
  tests/test_airbrakes.py
  tests/test_apogee_predictor.py
  tests/test_apogee_predictor_data_packet.py
  tests/test_context_packet.py
  tests/test_data_processor.py
  tests/test_imu.py
  tests/test_imu_data_packet.py
  tests/test_integration.py
  tests/test_logged_data_packet.py
  tests/test_logger.py
  tests/test_processed_data_packet.py
  tests/test_servo_packet.py
  tests/test_state.py
Labels: enhancement, data analysis

#132 Added the encoder to servo
  airbrakes/airbrakes.py
  airbrakes/data_handling/packets/logger_data_packet.py
  airbrakes/data_handling/packets/servo_data_packet.py
  airbrakes/hardware/servo.py
  tests/test_airbrakes.py
  tests/test_integration.py
  tests/test_servo.py
  tests/test_servo_packet.py
  tests/test_state.py
Labels: bug, enhancement, hardware

#131 Integrate camera
  .github/workflows/unit_tests.yml
  airbrakes/airbrakes.py
  airbrakes/constants.py
  airbrakes/hardware/camera.py
  airbrakes/main.py
  airbrakes/mock/display.py
  airbrakes/state.py
  pyproject.toml
  scripts/run_camera.py
  tests/conftest.py
  tests/test_airbrakes.py
  tests/test_integration.py
  uv.lock
Labels: enhancement

#136 Use arm64 runners on Github Actions
  .github/workflows/integration_tests.yml
  .github/workflows/unit_tests.yml
  airbrakes/data_handling/apogee_predictor.py
  tests/test_airbrakes.py
  tests/test_apogee_predictor.py
Labels: misc

#138 Fix bug, lots of tests and some restructuring
  .github/workflows/unit_tests.yml
  .pre-commit-config.yaml
  README.md
  airbrakes/airbrakes.py
  airbrakes/hardware/base_imu.py
  airbrakes/hardware/imu.py
  airbrakes/hardware/servo.py
  airbrakes/main.py
  airbrakes/mock/display.py
  airbrakes/mock/mock_imu.py
  airbrakes/mock/mock_logger.py
  airbrakes/state.py
  airbrakes/telemetry/__init__.py
  airbrakes/telemetry/apogee_predictor.py
  airbrakes/telemetry/data_processor.py
  airbrakes/telemetry/logger.py
  airbrakes/telemetry/packets/__init__.py
  airbrakes/telemetry/packets/apogee_predictor_data_packet.py
  airbrakes/telemetry/packets/context_data_packet.py
  airbrakes/telemetry/packets/imu_data_packet.py
  airbrakes/telemetry/packets/logger_data_packet.py
  airbrakes/telemetry/packets/processor_data_packet.py
  airbrakes/telemetry/packets/servo_data_packet.py
  pyproject.toml
  scripts/run_logger.py
  tests/auxil/utils.py
  tests/conftest.py
  tests/test_airbrakes.py
  tests/test_components/__init__.py
  tests/test_components/test_apogee_predictor.py
  tests/test_components/test_data_processor.py
  tests/test_components/test_logger.py
  tests/test_components/test_state.py
  tests/test_hardware/__init__.py
  tests/test_hardware/test_camera.py
  tests/test_hardware/test_imu.py
  tests/test_hardware/test_servo.py
  tests/test_integration.py
  tests/test_main.py
  tests/test_packets/__init__.py
  tests/test_packets/test_apogee_predictor_data_packet.py
  tests/test_packets/test_context_packet.py
  tests/test_packets/test_imu_data_packet.py
  tests/test_packets/test_logged_data_packet.py
  tests/test_packets/test_processed_data_packet.py
  tests/test_packets/test_servo_packet.py
  tests/test_utils.py
  uv.lock
Labels: bug, tests

#76 Generated Data Simulator
  README.md
  airbrakes/main.py
  airbrakes/simulation/README.md
  airbrakes/simulation/__init__.py
  airbrakes/simulation/data_generator.py
  airbrakes/simulation/random_config.py
  airbrakes/simulation/rotation_manager.py
  airbrakes/simulation/sim_config.py
  airbrakes/simulation/sim_imu.py
  airbrakes/simulation/sim_utils.py
  airbrakes/simulation/thrust_curves/AeroTech_J500G.csv
  airbrakes/simulation/thrust_curves/AeroTech_L1940X.csv
  airbrakes/telemetry/data_processor.py
  airbrakes/utils.py
  pyproject.toml
  tests/conftest.py
  tests/test_utils.py
Labels: enhancement

#140 Switch to Legacy Launch 1 configuration
  .github/workflows/integration_tests.yml
  .github/workflows/unit_tests.yml
  airbrakes/constants.py
  airbrakes/simulation/sim_config.py
  launch_data/README.md
  launch_data/metadata.json
  pyproject.toml
  tests/conftest.py
  uv.lock
Labels: misc

#144 Sound audible alarm if IMU is having issues in Standby
  airbrakes/mock/display.py
Labels: enhancement
