Repository NCSU-High-Powered-Rocketry-Club/AirbrakesV2, pull requests merged in 2025-03, with the labels that each got.

#161 Add Logger flushing
  airbrakes/constants.py
  airbrakes/mock/mock_imu.py
  airbrakes/telemetry/logger.py
  tests/test_components/test_logger.py
Labels: enhancement, do not merge (yet)

#167 Decent changes
  README.md
  airbrakes/constants.py
  airbrakes/context.py
  airbrakes/hardware/camera.py
  airbrakes/hardware/imu.py
  airbrakes/hardware/servo.py
  airbrakes/main.py
  airbrakes/mock/display.py
  airbrakes/mock/mock_camera.py
  airbrakes/mock/mock_imu.py
  airbrakes/mock/mock_servo.py
  airbrakes/state.py
  airbrakes/telemetry/apogee_predictor.py
  airbrakes/telemetry/data_processor.py
  airbrakes/telemetry/logger.py
  airbrakes/telemetry/packets/imu_data_packet.py
  airbrakes/telemetry/packets/logger_data_packet.py
  airbrakes/utils.py
  scripts/make_plots.ipynb
  scripts/plots/drop_test_speed.png
  scripts/plots/linear_mag_accel.png
  scripts/plots/previous_flight_accel_data.png
  scripts/plots/velocity_comparison.png
  scripts/run_buzzer.py
  scripts/run_hardware_pwm.py
  scripts/run_logger.py
  scripts/run_new_servo.py
  tests/conftest.py
  tests/test_airbrakes.py
  tests/test_components/test_data_processor.py
  tests/test_components/test_logger.py
  tests/test_hardware/test_servo.py
  tests/test_main.py
Labels: enhancement, needs pi to test

#166 `MockIMU` upgrades, `--mock-servo` & `--mock-camera` for `uv run real`
  README.md
  airbrakes/constants.py
  airbrakes/context.py
  airbrakes/hardware/camera.py
  airbrakes/hardware/imu.py
  airbrakes/hardware/servo.py
  airbrakes/main.py
  airbrakes/mock/display.py
  airbrakes/mock/mock_camera.py
  airbrakes/mock/mock_imu.py
  airbrakes/mock/mock_servo.py
  airbrakes/state.py
  airbrakes/telemetry/apogee_predictor.py
  airbrakes/telemetry/data_processor.py
  airbrakes/telemetry/logger.py
  airbrakes/telemetry/packets/imu_data_packet.py
  airbrakes/telemetry/packets/logger_data_packet.py
  airbrakes/utils.py
  launch_data/metadata.json
  scripts/make_plots.ipynb
  scripts/plots/drop_test_speed.png
  scripts/plots/linear_mag_accel.png
  scripts/plots/previous_flight_accel_data.png
  scripts/plots/velocity_comparison.png
  scripts/run_buzzer.py
  scripts/run_hardware_pwm.py
  scripts/run_logger.py
  scripts/run_new_servo.py
  tests/conftest.py
  tests/test_airbrakes.py
  tests/test_components/test_data_processor.py
  tests/test_components/test_logger.py
  tests/test_hardware/test_servo.py
  tests/test_main.py
  tests/test_utils.py
Labels: enhancement

#172 Use `os.fsync()` to guarantee disk write
  airbrakes/constants.py
  airbrakes/telemetry/logger.py
Labels: enhancement, needs pi to test

#173 Added altitude and vel fix for when airbrakes deploy
  airbrakes/constants.py
  airbrakes/context.py
  airbrakes/mock/display.py
  airbrakes/state.py
  airbrakes/telemetry/data_processor.py
  airbrakes/utils.py
  tests/auxil/launch_cases.py
  tests/test_components/test_data_processor.py
Labels: bug, enhancement

#176 Launch config for Pelicanator Flight 2
  airbrakes/constants.py
Labels: misc

#179 Use JIT / LLVM 20 built Python for performance improvements
  .github/workflows/benchmark.yml
  .github/workflows/integration_tests.yml
  .github/workflows/unit_tests.yml
  README.md
  tests/test_airbrakes.py
Labels: enhancement

#181 Adding integration back
  airbrakes/constants.py
  airbrakes/context.py
  airbrakes/main.py
  airbrakes/mock/display.py
  airbrakes/state.py
  airbrakes/telemetry/data_processor.py
  airbrakes/utils.py
  tests/conftest.py
  tests/test_components/test_data_processor.py
  tests/test_components/test_state.py
  tests/test_context.py
  tests/test_integration.py
  tests/test_main.py
Labels: enhancement
